### ISSUE TITLE
Link in message pushed to Slack is broken

### ISSUE THREAD

**Issue by ghost** [jenkinsci/slack-plugin#237]
correct link when using the Slack Plugin 1.8.1:

![slack-002](https://cloud.githubusercontent.com/assets/1623039/17080171/c8b4a3b2-5125-11e6-921e-13be6b58fb5f.png)

broken link when using the Slack Plugin 2.0.1:

![slack-001](https://cloud.githubusercontent.com/assets/1623039/17080172/c8d637f2-5125-11e6-8f38-bfe0451cbd02.png)

I use the plugin with the current version of Jenkins (2.14).

**Comment by johnnymn** [comment]
+1

**Comment by okuramasafumi** [comment]
We use the version `2.0.1` and encountered the same problem.
Is it the bug of Jenkins itself? We use Jenkins version `2.16`.

**Comment by alivespirit** [comment]
We use Jenkins 1.651.3 and have the same bug.

**Comment by kmadel** [comment]
This should be fixed with 2.1 release

**Comment by charleschen** [comment]
still seeing this problem (jenkins version: Jenkins 2.107.3, slack-plugin: 2.3)

**Comment by timja** [comment]
Fixed in 2.1 if you set the `Jenkins URL` in `Jenkins Location`
