### ISSUE TITLE
It sends notification twice

### ISSUE THREAD

**Issue by forluck2008** [jenkinsci/slack-plugin#322]
In my case, I need run the project on master node. So I configured the Matrix to run it on master as following.
<img width="443" alt="screen shot 2017-06-02 at 7 39 12 am" src="https://cloud.githubusercontent.com/assets/21351627/26702043/a1819024-4766-11e7-848b-a793fb05d788.png">

Hereunder is the duplicate message see on Slack. It triggers message sending twice with and without the node label (master).
<img width="472" alt="screen shot 2017-06-02 at 7 40 56 am" src="https://cloud.githubusercontent.com/assets/21351627/26702091/d7ece6ae-4766-11e7-8986-60d3872d7c3f.png">

**Comment by chris-malloy-mri** [comment]
I'm also getting this, although I have the job configured to run on slave.

**Comment by malli312** [comment]
HI Team,
We are getting double notifications to slack channel through Jenkins, how can we control double and duplicate notifications, please help us to sort it out. we are getting while running the build jobs from Jenkins.
And we are using slack notifier plugin version 2.3, please find the sample output in attachments 
![selection_142](https://user-images.githubusercontent.com/23642210/30901304-db085ef2-a384-11e7-9ac5-1593cc10973c.png)
![selection_141](https://user-images.githubusercontent.com/23642210/30901305-db0c64f2-a384-11e7-8f6a-7c92797a01cf.png)

**Comment by sniederb** [comment]
Have the same issue. Maven multi-module build, posts were not doubled Oct 9th, but since yesterday they are. (not sure, we might've upgraded from 2.2 to 2.3 in between)

**Comment by jacek-debowczyk** [comment]
Sam problem. Config in attachment
![obraz](https://user-images.githubusercontent.com/28861488/32101691-84865c26-bb19-11e7-8dab-33fa5b5ee79f.png)

**Comment by iKeirNez** [comment]
Same issue here, it's quite annoying :/

**Comment by marfous** [comment]
We are facing the same issue. There is configured to notify for every result and the notifications are doubled.

**Comment by chanukov** [comment]
Same issue with failures not just successes

**Comment by arpiatek** [comment]
anyone found a workaround?

**Comment by gitAllender** [comment]
Hi. Some news here?

**Comment by Xaseron** [comment]
I'm running into the same issue, when i configure url, channel and token global. 
I solved this problem in the pipeline when i explicitly configure url, channel and credentials.
e.g. :
```
slackSend baseUrl: 'slackurl', channel: '#deployment', message: 'TEST1337', tokenCredentialId: 'slack-bot'
```

**Comment by arpiatek** [comment]
Thanks Michael. We used jobs with slack message on post build for a temporary fix. Thanks for this better pipeline script solution.

**Comment by egarkavy** [comment]
@Xaseron @arpiatek 
Can you help me, where can I edit that pipeline? I am using TC 2018.1.1 version

**Comment by Xaseron** [comment]
This plugin is only for Jenkins. I don't know how to fix this for TeamCity. It seems that this is an inherent problem with slack.

**Comment by landaumd** [comment]
Any news on this issue? I am using Jenkins and scripted pipeline and all notifications are being sent twice.

**Comment by pumazi** [comment]
I'm observing this issue as well. I'm using the Declarative Pipeline with this plugin at version 2.3.

I've placed the `${env.BUILD_ID}` in my output messages. A previous BUILD_ID value shows up in the second message. The message is from the current commit even thought the previous build mentioned in the second message uses a completely different message.

<details>
<summary>example of the different messages</summary>

If the current build is `30` with a commit adjusting the slack message to `slackSend "-- ${env.BUILD_ID} --"` and the previous commit's message was `slackSend "+=+ ${env.BUILD_ID} +=+"` then we see something like:

```
...
jenkins: +=+ 19 +=+
...
jenkins: +=+ 29 +=+
jenkins: +=+ 18 +=+
jenkins: -- 30 --
jenkins: -- 19 --
```
Where the last two lines are from the current build.

</details>
<br/>

The only visible pattern appears to be the incrementing of the BUILD_ID. If I rerun a job manually, only one message is sent. If it is triggered by a commit, two messages are sent.

I've tried only defining settings in the "Configure System" and then again in the `slackSend` line itself.

There doesn't appear to be any pattern or good reason why this happens.

**Comment by borisivan** [comment]
I'm seeing this as well. Too many notifications sent twice. If I can determine a common pattern that makes it happen I'll update. But seeing this daily.

**Comment by dchivescu-gpsw** [comment]
How is this not a priority?! $20 on me for the first approved PR fixing the issue, ONCE IT'S IN PRODUCTION. (Revolut request the $20)

2019 in a few, and I'm still spamming the 💩💩💩  out of all the Slack pager-duty channels where I have my regression hooked in.

**Comment by timja** [comment]
What version of the slack plugin are you using?
There was a PR that may have helped here:
https://github.com/jenkinsci/slack-plugin/pull/446

**Comment by vitalis** [comment]
> What version of the slack plugin are you using?
> There was a PR that may have helped here:
> #446

It doesn't solve the issue when running with Matrix

**Comment by Cyberbeni** [comment]
I thought I commented on this issue before... If notifyRegression is turned on then both this line https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/ActiveNotifier.java#L118 and this line https://github.com/jenkinsci/slack-plugin/blob/master/src/main/java/jenkins/plugins/slack/ActiveNotifier.java#L150 will trigger the notification.

**Comment by timja** [comment]
Have you tried that on a recent release @Cyberbeni it was changed a few versions ago to run after finalising?

**Comment by Cyberbeni** [comment]
@timja 
All plugins got updated 2 days ago and it doesn't send test notification when clicking test connection but says success (after checking the bot user flag on top of what we had in the previous version)

My main language is not Java and I usually don't look at jenkins (plugin) code but I'm pretty sure that still works as it was 3-4 months ago when I turned off notifyRegression and stopped getting duplicate notifications.

**Comment by dreis2211** [comment]
Hi. Is there any progress on that one? We're hitting that on our Jenkins as well.
```

**Comment by timja** [comment]
Can you include more info on your setup @dreis2211 
Is it a matrix job?
Were there any concurrent builds? 

There has been fixes around this, and an unreleased change on master which may affect it (https://github.com/jenkinsci/slack-plugin/pull/576)

**Comment by dreis2211** [comment]
It's actually build-flow job(s) that we didn't get rid of yet. No concurrency, the problem is not really dependent on the environment it's running on (happens both on master and on nodes).

**Comment by timja** [comment]
Ok can't help too much there, flow has got a strong do not use warning on it afaik...

I would hope it wouldn't be much work to migrate them off that.

**Comment by timja** [comment]
Is this still an issue?

**Comment by dlakatos847** [comment]
Yes. Latest version still sends 2 notifications.

**Comment by timja** [comment]
Closing this issue can someone open a new issue with clean information showing that they have configured, 
job-dsl / config.xml would be ideal

There's been no response in months, as far as I know it has been fixed

**Comment by monkpit** [comment]
@timja  I am still having this issue, not sure about everyone else.

**Comment by Saibamen** [comment]
I still have this issue

**Comment by timja** [comment]
As stated above please open a new issue with configuration and clear steps to reproduce
