### ISSUE TITLE
Slack-API Notifications no longer working

### ISSUE THREAD

**Issue by tracom1** [jenkinsci/slack-plugin#545]
We've upgraded our slack-plugin from 2.18 to 2.19, and can no longer publish notifications to our slack channels.  We receive the following error:

```12:59:51  Slack Send Pipeline step running, values are - baseUrl: <empty>, teamDomain: scout24, channel: de-notifications, color: good, botUser: true, tokenCredentialId: slack-api-token
12:59:51  ERROR: Slack notification failed with exception: java.lang.IllegalArgumentException: the token with the provided ID could not be found and no token was specified
```

We are configuring and using the token by using the following XML configuration:

```
<tokenCredentialId>slack-api-token</tokenCredentialId>
```

We've also tried setting the teamDomain, with no success.  Since this worked prior to upgrading to 2.19, I'm guessing this is related to the folder credential support added in PR-541(https://github.com/jenkinsci/slack-plugin/pull/541)

**Comment by timja** [comment]
Are you using freestyle jobs or pipeline?

What scope is the credential set at?

**Comment by tracom1** [comment]
We're using pipeline, and the credential is set globally.

**Comment by timja** [comment]
For the credential can you check the scope please?
![image](https://user-images.githubusercontent.com/21194782/54996262-b9247480-4fc0-11e9-9462-8b39a26e1aaa.png)

URL something like:
https://<jenkins-url>/credentials/store/system/domain/_/credential/slack-token/update

**Comment by tracom1** [comment]
Scope is Jenkins and nodes only.

**Comment by timja** [comment]
Needs to be updated to global, System means it's not available to jobs

We're now Job context aware to allow supporting folder credentials, it has an impact that any previously working System credentials won't work.

**Comment by tracom1** [comment]
Ok, that's good to know.  I'll try that

**Comment by esproul** [comment]
I just updated from 2.18 to 2.20 and I am still seeing the error that the OP reported.  I double-checked that my existing credential is global-scope and is called "Migrated slack token". When I test connection from the global Jenkins configuration, it works, but from a job (even one which contains no overrides of the global settings), it fails with the illegal argument exception.

I note that the menu for "Integration Token Credential ID" has no options other than "none". I believe I should be able to select my existing credential there, but I'm not sure if that's just for overriding too.

**Comment by timja** [comment]
@esproul https://github.com/jenkinsci/slack-plugin/issues/545#issuecomment-476600165

**Comment by esproul** [comment]
@timja I'm confused; I saw that comment, and I already checked that my credential is set to global scope, not system.  Did I miss something?

**Comment by esproul** [comment]
![jenkins_cred](https://user-images.githubusercontent.com/731614/55341830-5e35c600-5475-11e9-9084-7607f0d21545.png)

**Comment by esproul** [comment]
I will soon; I had to downgrade the plugin to get notifications working again, and as soon as there is a lull I will upgrade the plugin again and try the update on the credential.  Thanks for the help!

**Comment by timja** [comment]
you can update the credential separately, Global will work on both versions of the plugin

**Comment by esproul** [comment]
Oh, hah. In the Update screen for the token, "Scope" was set to System there. I missed that before, thinking the "global" that I saw on the main Credentials screen meant the token was global.  I've set it to Global now so it will probably work when I re-upgrade the plugin.  Thanks again.

**Comment by esproul** [comment]
@timja Confirmed, after change to token scope, 2.20 works as expected. Sorry for the noise, but I appreciate you clearing up my confusion.

**Comment by jsoref** [comment]
@timja : this isn't cool. If you make a breaking change like this, you *must* mark it as breaking so that when people upgrade they will get a nice red warning about incompatible settings.

For example:
> SSH SlavesAllows to launch agents over SSH, using a Java implementation of the SSH protocol.

**Warning: the new version of this plugin claims to use a different settings format than the installed version. Jobs using this plugin may need to be reconfigured, and/or you may not be able to cleanly revert to the prior version without manually restoring old settings. Consult the plugin release notes for details.**

**Comment by timja** [comment]
@jsoref there was a bug in the migration, it should have been compatible.
It would be marked incompatible if it was intentionally incompatible.

believe me there's a number of methods and code I want to remove in this plugin but I'm keeping them for backwards compatibly.

90% of the review I do on changes is for backwards compatibility fixes

**Comment by darmbrust** [comment]
What is the actual fix for this?  I just tried integrating with this plugin, and am still getting the same error.  I'm injecting the token as a global secret using the Configuration As Code plugin (into my docker image for jenkins), and the end result is 

ERROR: Slack notification failed with exception: java.lang.IllegalArgumentException: the token with the provided ID could not be found and no token was specified

Even though the specified token id is correct in the debug output above:
tokenCredentialId: slack-token

And a global credential exists with the correct value.

**Comment by darmbrust** [comment]
It turns out, I still had a bug in my docker build, that was causing the token "secret" portion to be an empty string, instead of the correct value.  But the error message provided when this happened was still wrong - it shouldn't say that the provided ID could not be found, because it could be found - it is just that the provided ID had the incorrect (empty) value in my case.

**Comment by timja** [comment]
Feel free to send a PR for this edge case @darmbrust 
The reason you're confused is that two error messages are combined into one.
it could either be cred not found or empty token.

**Comment by dashfwd** [comment]
To all reading this thread ... upgrading to version 2.30 of the plugin completely broke Slack notifications (w/Jenkins ver. 2.189).  No amount changing credential scopes worked.  In fact, I wasn't able to use any existing credentials, and when I tried to create new ones I wasn't able to select the new one that I created.

Solution that worked for me: Revert to version 2.28 and re-select credentials, and then things worked fine again.

**Comment by timja** [comment]
File a new issue please

**Comment by dashfwd** [comment]
Done: https://github.com/jenkinsci/slack-plugin/issues/609

**Comment by evertonevaristo** [comment]
Hello All, I'm still facing this issue at Jenkins 2.204.1 and plugin 2.36, does anyone know how to solve this?

**Comment by jsoref** [comment]
@evertonevaristo: Please file a new issue. (This stuff is apparently moderately fragile as it has since been broken and fixed again at least once before, c.f. https://github.com/jenkinsci/slack-plugin/issues/545#issuecomment-522141530.)

**Comment by evertonevaristo** [comment]
@jsoref thank you!
