### ISSUE TITLE
not sending two successive notifications in slack

### ISSUE THREAD

**Issue by vishal-elimu** [jenkinsci/slack-plugin#858]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

OS : Ubuntu 18:04
Jenkins-agent : Same host (Ubuntu 18:04)
Jenkins version: Jenkins 2.346.2

### Reproduction steps

1. Enabled "Notify Success" in post build action in jenkins job. (**Jenkins version 2.346.2, Slack Notification Plugin version 
Version631.v40deea_40323b)**
2. Ran the same jenkins job twice. I get notification only for one build of job 
3. Get notification on alternate build/run of job. Example: gets slack notification for job's build number 2, 4, 6, 8 so jenkins/slack notification plugin skips every alternate build notification.

![image](https://user-images.githubusercontent.com/113007870/202678627-ffeff062-e497-49a9-8fcd-cbe588b73f22.png)

### Expected Results

1. Upon every successfully build / run of job I should get notification
2. When job fails I should get "Job Failed" notification/message
3. When job fails but next build of job runs successfully then I should get notification with "back to normal" message

### Actual Results

1. If job fails (consider build no : 4) and then next build (build no: 5) runs successfully then I should get notified with "back to normal " notification but it does not. I get notification for "failed build" (build no : 4) but not for next build (build no : 5)
2. Sometimes when job fails I don't get notification (consider build no: 6) but I get notification (back to normal) when next build of job runs successfully (build no: 7)
3. When job runs successfully twice (consider build no 8 and 9) I only get notification for build no : 8
4. My observation is that jenkins/plugin not sending two successive notifications in slack and it skips one notification
![image](https://user-images.githubusercontent.com/113007870/202685781-79630729-47dd-47e8-a0b0-0082c60bfa5b.png)
![image](https://user-images.githubusercontent.com/113007870/202687007-591b90d5-1a0d-40b1-afe6-2613362a2a10.png)

**Comment by thomasvincent** [comment]
I ran into the same thing, and I believe it was fixed in the latest version of the plugin. My work around the problem was by using the slackNotify step
```
pipeline {
  agent any

  stages {
    stage('Build') {
      steps {
        echo 'Building...'
      }
    }

    stage('Notify Slack') {
      steps {
        slackNotify channel: '#general', message: 'Build successful!'
      }
    }
  }
}
```

**Comment by timja** [comment]
you mustn't have the slack plugin installed then or it's failed to start

**Comment by vishal-elimu** [comment]
@timja  slack plugin is installed and using version `631.v40deea_40323b` 
I am able to use `slackSend` commands in pipeline steps but issue still persist, not able to set 2 successive slack notifications (I do receive every alternate slack notification).

**Comment by timja** [comment]
Ah right my mistake.

**Comment by vishal-elimu** [comment]
@timja , @thomasvincent I just updated jenkins logs above, 

I am seeing a lot `WARNING	j.p.slack.StandardSlackService#postToSlack: Error posting to Slack javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated at ` messages in jenkins container. 

Do you guys have an idea about these warning messages ? 

- Thanks

**Comment by timja** [comment]
possibly outdated system libraries or a MITM proxy on your side?

Basically a network issue specific to you.

see also https://github.com/jenkinsci/slack-plugin/issues/837#issuecomment-1206810299

**Comment by vishal-elimu** [comment]
Thanks Tim, I will take a look
